### ISSUE TITLE
git add -A

### ISSUE THREAD

**Issue by baudo2048** [CorsoJavaGenesis/Common#1]
Tra i comandi che abbiamo visto oggi a lezione, a che serve il comando in oggetto?

**Comment by WildistheStorm** [comment]
aggiunge i file elencati in seguito al comando all'index

**Comment by mariodavino** [comment]
aggiorna l'index totalmente e prepara all'aggiunta di file

**Comment by baudo2048** [comment]
Per me è chiaro quello che avete risposto. Mi sorgono però nuovi interrogativi: E' a seguito di tale comando che viene creato l'oggetto commit? Cosa è la index? Posso rimuovere dei files dalla index?

**Comment by baudo2048** [comment]
#4
