### ISSUE TITLE
Errori nei package

### ISSUE THREAD

**Issue by baudo2048** [CorsoJavaGenesis/Common#2]
Ho aggiornato il mio working tree e in tutti i file ci sono degli errori sui package. Cosa devo fare per
metterli a posto?
Se modifico per esempio la classe ContoCorrente.java con la seguente riga:

`package corsojavagenesis.common.helloworldarray.src.helloeclipse.ContoCorrente;`

allora l'errore sparisce.

Considerato che si tratta di un progetto maven e riflettendo sulla struttura delle cartelle secondo
le convenzioni di maven (src/main/java) cosa sarebbe meglio fare?

**Comment by WildistheStorm** [comment]
spostare i file?

**Comment by baudo2048** [comment]
Ok quindi abbiamo fatto un pò di refactoring. Sì spostato file e/o rinominato i packages.
Direi che oggi abbiamo messo a posto e pertanto chiudo la issue. Se cmq qualcosa non è chiara è possibile riaprire la issue. Grazie @WildstheStorm

**Comment by baudo2048** [comment]
@WildistheStorm
